// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/ensambladoresproyecto/Lexer.flex

package ensambladoresproyecto;
import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\4\1\0"+
    "\1\5\1\0\1\6\2\0\1\7\1\10\1\11\2\0"+
    "\1\12\1\13\1\14\1\0\2\15\10\16\1\17\1\20"+
    "\3\0\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\0\1\56"+
    "\1\0\1\43\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\12\0\1\3\73\0"+
    "\1\43\7\0\1\43\3\0\1\43\3\0\1\43\1\0"+
    "\1\43\6\0\1\43\1\0\1\43\4\0\1\43\7\0"+
    "\1\43\3\0\1\43\3\0\1\43\1\0\1\43\6\0"+
    "\1\43\1\0\1\43\63\0\2\57\115\0\1\60\u01a8\0"+
    "\2\3\u0100\0\1\61\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\2\1\1\2\3\1\2"+
    "\1\4\1\1\20\4\3\1\1\0\1\5\7\0\1\6"+
    "\1\7\1\0\1\10\2\4\1\11\1\4\1\11\3\4"+
    "\1\11\1\4\1\12\1\11\1\4\1\12\1\11\1\7"+
    "\6\4\1\13\1\4\1\13\13\4\1\0\1\4\11\0"+
    "\1\4\6\0\1\13\6\4\1\0\4\4\1\0\2\4"+
    "\1\0\4\4\4\0\1\3\5\0\1\4\1\0\1\4"+
    "\1\0\2\4\1\0\1\4\1\0\1\4\2\0\1\12"+
    "\20\0\1\14\5\0\1\12\1\0\1\15\1\16\11\0"+
    "\1\12";

  private static int [] zzUnpackAction() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\u012c"+
    "\0\u015e\0\u0190\0\u01c2\0\62\0\u01f4\0\u0226\0\u0258\0\u028a"+
    "\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a"+
    "\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa"+
    "\0\226\0\226\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6"+
    "\0\u0708\0\u0708\0\62\0\u073a\0\62\0\u076c\0\u079e\0\u0352"+
    "\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\62\0\u08ca\0\u0320"+
    "\0\u08fc\0\u092e\0\u0352\0\u0960\0\u0352\0\u0992\0\u09c4\0\u09f6"+
    "\0\u0a28\0\u0a5a\0\u0a8c\0\u0352\0\u0abe\0\62\0\u0af0\0\u0b22"+
    "\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2"+
    "\0\u0ce4\0\u0546\0\u0546\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde"+
    "\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\226\0\u0ed8\0\u0f0a\0\u0f3c"+
    "\0\u0f6e\0\u0fa0\0\u0fd2\0\u0320\0\u1004\0\u1036\0\u1068\0\u109a"+
    "\0\u10cc\0\u08fc\0\u0960\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6"+
    "\0\u11f8\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356"+
    "\0\u1388\0\u13ba\0\u13ec\0\62\0\u141e\0\u1450\0\u1482\0\u14b4"+
    "\0\u14e6\0\u1518\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612\0\u1644"+
    "\0\u1676\0\u16a8\0\u16da\0\u170c\0\u173e\0\u1770\0\u17a2\0\u17d4"+
    "\0\u1806\0\u1838\0\u186a\0\u189c\0\u18ce\0\u1900\0\u1932\0\u1770"+
    "\0\u1964\0\u1996\0\u19c8\0\u19fa\0\u1a2c\0\u1a5e\0\62\0\u1a90"+
    "\0\u1ac2\0\u1af4\0\u1b26\0\u1b58\0\u186a\0\u1b8a\0\62\0\62"+
    "\0\u1bbc\0\u1bee\0\u1c20\0\u1c52\0\u1c84\0\u1cb6\0\u1ce8\0\u1d1a"+
    "\0\u1d4c\0\62";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\2\1\5\1\6"+
    "\1\2\1\7\1\2\1\10\1\11\1\12\1\2\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\2\24\1\25\1\26\1\24\1\27\1\30\2\24\1\31"+
    "\2\24\1\32\1\33\2\24\1\34\1\35\2\24\1\36"+
    "\1\2\1\37\1\40\1\2\63\0\2\3\1\0\1\3"+
    "\55\0\2\41\2\0\1\41\1\42\1\41\1\42\54\41"+
    "\2\0\1\41\1\42\1\43\1\42\52\41\13\0\1\44"+
    "\73\0\1\45\1\46\10\0\1\47\5\0\1\50\12\0"+
    "\1\50\16\0\1\11\1\12\4\0\1\51\1\52\4\51"+
    "\1\0\1\53\44\0\2\12\4\0\6\51\1\0\1\53"+
    "\27\0\2\13\2\0\56\13\26\0\1\54\50\0\2\23"+
    "\1\55\3\0\1\56\2\23\1\57\2\23\1\24\1\60"+
    "\3\24\1\60\13\24\1\60\2\24\22\0\2\23\1\55"+
    "\3\0\6\23\1\24\1\60\3\24\1\60\3\24\1\60"+
    "\7\24\1\60\1\61\1\24\22\0\2\23\1\55\3\0"+
    "\6\23\1\24\1\60\3\24\1\62\1\63\1\24\1\64"+
    "\3\24\1\60\3\24\1\65\1\60\2\24\3\0\1\66"+
    "\16\0\2\23\1\55\3\0\1\67\1\70\4\23\1\24"+
    "\1\60\1\71\2\24\1\60\6\24\1\60\1\24\1\72"+
    "\1\24\1\73\1\60\2\24\2\0\1\74\1\66\16\0"+
    "\2\23\1\55\3\0\6\23\1\24\1\75\5\24\1\76"+
    "\4\24\1\60\7\24\3\0\1\66\16\0\2\23\1\55"+
    "\3\0\6\23\1\24\1\75\22\24\22\0\2\24\1\55"+
    "\3\0\32\24\22\0\2\24\1\55\3\0\3\24\1\77"+
    "\10\24\1\100\4\24\1\101\10\24\22\0\2\24\1\55"+
    "\3\0\1\102\1\24\1\103\10\24\1\104\1\24\1\105"+
    "\4\24\1\104\7\24\3\0\1\106\16\0\2\24\1\55"+
    "\3\0\3\24\1\105\1\107\11\24\1\110\13\24\22\0"+
    "\2\24\1\55\3\0\16\24\1\111\13\24\22\0\2\24"+
    "\1\55\3\0\16\24\1\112\5\24\1\113\5\24\22\0"+
    "\2\24\1\55\3\0\2\24\1\114\4\24\1\115\1\60"+
    "\6\24\1\60\2\24\1\60\1\116\6\24\2\0\2\66"+
    "\16\0\2\24\1\55\3\0\4\24\1\117\25\24\22\0"+
    "\2\24\1\55\3\0\16\24\1\120\13\24\22\0\2\24"+
    "\1\55\3\0\2\24\1\121\27\24\5\0\2\122\2\0"+
    "\52\122\1\123\3\122\26\0\1\124\10\0\1\125\1\126"+
    "\3\0\1\127\40\0\1\130\1\0\1\131\4\0\1\132"+
    "\1\66\6\0\1\66\2\0\1\66\1\133\1\134\7\0"+
    "\2\66\1\0\2\41\2\0\1\41\1\42\1\41\1\135"+
    "\52\41\15\0\2\136\104\0\1\137\43\0\1\140\77\0"+
    "\1\141\66\0\1\142\30\0\2\51\4\0\6\51\1\0"+
    "\1\53\52\0\1\143\53\0\2\23\1\55\3\0\3\23"+
    "\1\144\2\23\1\24\1\75\22\24\3\0\1\14\16\0"+
    "\2\23\1\55\3\0\3\23\1\144\2\23\1\24\1\75"+
    "\22\24\22\0\2\24\1\55\3\0\23\24\1\145\6\24"+
    "\22\0\2\24\1\55\3\0\3\24\1\104\26\24\2\0"+
    "\1\14\17\0\2\24\1\55\3\0\17\24\1\146\12\24"+
    "\22\0\2\24\1\55\3\0\3\24\1\147\26\24\22\0"+
    "\2\24\1\55\3\0\3\24\1\104\26\24\22\0\2\23"+
    "\1\55\3\0\6\23\1\24\1\75\13\24\1\150\6\24"+
    "\3\0\1\14\16\0\2\24\1\55\3\0\25\24\1\104"+
    "\4\24\22\0\2\24\1\55\3\0\17\24\1\151\12\24"+
    "\55\0\1\106\26\0\2\24\1\55\3\0\3\24\1\105"+
    "\26\24\22\0\2\24\1\55\3\0\10\24\1\152\21\24"+
    "\2\0\1\153\17\0\2\24\1\55\3\0\24\24\1\115"+
    "\5\24\22\0\2\24\1\55\3\0\4\24\1\154\25\24"+
    "\22\0\2\24\1\55\3\0\4\24\1\104\25\24\22\0"+
    "\2\24\1\55\3\0\27\24\1\155\2\24\22\0\2\24"+
    "\1\55\3\0\22\24\1\104\7\24\3\0\1\106\16\0"+
    "\2\24\1\55\3\0\32\24\3\0\1\14\16\0\2\24"+
    "\1\55\3\0\3\24\1\146\12\24\1\156\13\24\22\0"+
    "\2\24\1\55\3\0\25\24\1\157\4\24\22\0\2\24"+
    "\1\55\3\0\17\24\1\104\12\24\22\0\2\24\1\55"+
    "\3\0\32\24\3\0\1\160\16\0\2\24\1\55\3\0"+
    "\1\161\31\24\22\0\2\24\1\55\3\0\13\24\1\104"+
    "\16\24\22\0\2\24\1\55\3\0\1\162\2\24\1\104"+
    "\12\24\1\146\13\24\2\0\1\14\17\0\2\24\1\55"+
    "\3\0\32\24\3\0\1\163\16\0\2\24\1\55\3\0"+
    "\21\24\1\164\10\24\22\0\2\24\1\55\3\0\7\24"+
    "\1\165\22\24\40\0\1\153\23\0\1\153\51\0\1\132"+
    "\37\0\1\166\20\0\1\167\42\0\1\170\76\0\1\14"+
    "\40\0\1\171\74\0\1\106\46\0\1\172\1\0\1\14"+
    "\1\106\4\0\1\14\5\0\1\173\15\0\1\14\26\0"+
    "\1\14\46\0\1\174\3\0\2\136\71\0\1\175\101\0"+
    "\1\176\41\0\1\177\56\0\1\200\104\0\1\201\30\0"+
    "\2\24\1\55\3\0\4\24\1\202\25\24\22\0\2\24"+
    "\1\55\3\0\32\24\3\0\1\203\16\0\2\24\1\55"+
    "\3\0\4\24\1\204\25\24\22\0\2\24\1\55\3\0"+
    "\1\204\31\24\15\0\1\205\4\0\2\24\1\55\3\0"+
    "\32\24\22\0\2\24\1\55\3\0\23\24\1\104\6\24"+
    "\22\0\2\24\1\55\3\0\31\24\1\104\22\0\2\24"+
    "\1\55\3\0\17\24\1\206\12\24\22\0\2\24\1\55"+
    "\3\0\22\24\1\207\7\24\3\0\1\210\33\0\1\211"+
    "\44\0\2\24\1\55\3\0\32\24\3\0\1\212\16\0"+
    "\2\24\1\55\3\0\2\24\1\213\27\24\53\0\1\14"+
    "\30\0\2\24\1\55\3\0\3\24\1\202\26\24\22\0"+
    "\2\24\1\55\3\0\6\24\1\104\23\24\43\0\1\214"+
    "\64\0\1\14\66\0\1\106\60\0\1\212\12\0\1\212"+
    "\26\0\1\215\101\0\1\203\12\0\1\203\30\0\1\216"+
    "\55\0\1\216\65\0\1\217\57\0\1\220\57\0\1\14"+
    "\42\0\1\221\10\0\2\24\1\55\3\0\32\24\31\0"+
    "\1\14\24\0\1\14\14\0\1\222\10\0\2\24\1\55"+
    "\3\0\32\24\12\0\1\223\1\0\1\223\1\224\4\0"+
    "\1\225\1\226\4\0\6\227\46\0\2\24\1\55\3\0"+
    "\15\24\1\102\14\24\22\0\2\24\1\55\3\0\26\24"+
    "\1\104\3\24\31\0\1\14\24\0\1\106\33\0\1\14"+
    "\4\0\1\14\102\0\1\14\25\0\2\24\1\55\3\0"+
    "\12\24\1\204\17\24\4\0\1\230\47\0\1\231\47\0"+
    "\1\230\23\0\1\230\4\0\1\222\113\0\1\232\60\0"+
    "\1\216\23\0\1\216\42\0\1\233\64\0\1\234\12\0"+
    "\1\234\1\0\2\223\2\0\1\223\1\235\1\223\1\235"+
    "\52\223\13\0\1\236\57\0\1\237\3\0\1\225\1\226"+
    "\4\0\1\227\1\240\4\227\1\0\1\241\40\0\1\237"+
    "\3\0\2\226\4\0\6\227\1\0\1\241\44\0\2\227"+
    "\4\0\6\227\1\0\1\241\55\0\1\242\37\0\1\243"+
    "\123\0\1\130\42\0\1\244\32\0\2\223\2\0\1\223"+
    "\1\235\1\223\1\235\1\223\1\245\50\223\15\0\2\246"+
    "\54\0\1\247\3\0\2\227\4\0\6\227\1\0\1\241"+
    "\40\0\1\250\77\0\1\14\77\0\1\251\12\0\1\251"+
    "\32\0\1\252\41\0\1\253\3\0\2\246\102\0\1\254"+
    "\61\0\1\255\33\0\1\237\73\0\1\256\65\0\1\257"+
    "\70\0\1\260\63\0\1\261\57\0\1\262\71\0\1\262"+
    "\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7550];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\4\1\1\11\24\1\1\0"+
    "\1\1\7\0\1\1\1\11\1\0\1\11\10\1\1\11"+
    "\17\1\1\11\13\1\1\0\1\1\11\0\1\1\6\0"+
    "\7\1\1\0\4\1\1\0\2\1\1\0\4\1\4\0"+
    "\1\11\5\0\1\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\2\0\1\1\20\0\1\11\5\0"+
    "\1\1\1\0\2\11\11\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
    return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "Error", yyline, yycolumn);
            }
            // fall through
          case 15: break;
          case 2:
            { /* Ignorar */
            }
            // fall through
          case 16: break;
          case 3:
            { return token(yytext(), "Numero Decimal", yyline, yycolumn);
            }
            // fall through
          case 17: break;
          case 4:
            { return token(yytext(), "Simbolo", yyline, yycolumn);
            }
            // fall through
          case 18: break;
          case 5:
            { return token(yytext(), "Constante", yyline, yycolumn);
            }
            // fall through
          case 19: break;
          case 6:
            { return token(yytext(), "Numero Binario", yyline, yycolumn);
            }
            // fall through
          case 20: break;
          case 7:
            { return token(yytext(), "Numero Hexadecimal", yyline, yycolumn);
            }
            // fall through
          case 21: break;
          case 8:
            { return token(yytext(), "Etiqueta", yyline, yycolumn);
            }
            // fall through
          case 22: break;
          case 9:
            { return token(yytext(), "Registro", yyline, yycolumn);
            }
            // fall through
          case 23: break;
          case 10:
            { return token(yytext(), "Pseudoinstruccion", yyline, yycolumn);
            }
            // fall through
          case 24: break;
          case 11:
            { return token(yytext(), "Instruccion", yyline, yycolumn);
            }
            // fall through
          case 25: break;
          case 12:
            { return token(yytext(), "Pseudoinstruccion y constante decimal", yyline, yycolumn);
            }
            // fall through
          case 26: break;
          case 13:
            { return token(yytext(), "Pseudoinstruccion y constante binario", yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 14:
            { return token(yytext(), "Pseudoinstruccion y constante hexadecimal", yyline, yycolumn);
            }
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
